//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1CarRental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int id { get; set; }
        public string name { get; set; }
        public string shortname { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
